---
- name: to install
  hosts: all
  vars:
   - a: git
   - b: present
   - c: yes  
  tasks:
   - name: to install
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...

